_target_: src.models.energy_forecasting.encoder.LatentEncoder
energy_architecture: fcn
latent_energy_size: ${mul:${forecast_horizon},2}
weather_architecture: fcn
latent_weather_size: ${mul:${forecast_horizon},2}
weather_horizon: ${data.weather.weather_horizon}
upper_left: ${data.weather.upper_left}
lower_right: ${data.weather.lower_right}
scaling: ${data.weather.scaling}
calendar_architecture: flatten
latent_calendar_size: null